# Generated by Django 6.1 on 2026-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Google Places')),
                ('name', models.CharField(max_length=255, verbose_name='empresa')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='endereço')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('website_url', models.URLField(blank=True, max_length=1000, verbose_name='site')),
                ('google_maps_url', models.URLField(blank=True, max_length=1000, verbose_name='Google Maps')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='avaliação')),
                ('user_rating_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de avaliações')),
                ('source_query', models.CharField(blank=True, max_length=500, verbose_name='termo pesquisado')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('interested', 'Interessado'), ('not_interested', 'Sem interesse')], default='new', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'prospect',
                'verbose_name_plural': 'prospects',
                'ordering': ['name'],
            },
        ),
    ]
