# Generated by Django 6.1 on 2026-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='contatado em'),
        ),
    ]
